/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const services = sqliteTable(
  'services',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    slug: text('slug').notNull(),
    description: text('description').notNull(),
    detail: text('detail').notNull(),
    duration: numeric('duration', { mode: 'number' }).notNull().default(60),
    price: numeric('price', { mode: 'number' }),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    body: text('body', { mode: 'json' }).notNull(),
    featuredOnHome: integer('featured_on_home', { mode: 'boolean' }).default(true),
    order: numeric('order', { mode: 'number' }).default(1),
    status: text('status', { enum: ['published', 'draft'] }).default('published'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('services_slug_idx').on(columns.slug),
    index('services_image_idx').on(columns.image),
    index('services_updated_at_idx').on(columns.updatedAt),
    index('services_created_at_idx').on(columns.createdAt),
  ],
)

export const slots = sqliteTable(
  'slots',
  {
    id: integer('id').primaryKey(),
    date: text('date').notNull(),
    startTime: text('start_time').notNull(),
    endTime: text('end_time').notNull(),
    service: integer('service_id').references(() => services.id, {
      onDelete: 'set null',
    }),
    status: text('status', { enum: ['available', 'booked', 'blocked'] })
      .notNull()
      .default('available'),
    notes: text('notes'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('slots_date_idx').on(columns.date),
    index('slots_service_idx').on(columns.service),
    index('slots_status_idx').on(columns.status),
    index('slots_updated_at_idx').on(columns.updatedAt),
    index('slots_created_at_idx').on(columns.createdAt),
  ],
)

export const bookings = sqliteTable(
  'bookings',
  {
    id: integer('id').primaryKey(),
    clientName: text('client_name').notNull(),
    clientEmail: text('client_email').notNull(),
    clientPhone: text('client_phone'),
    service: integer('service_id')
      .notNull()
      .references(() => services.id, {
        onDelete: 'set null',
      }),
    slot: integer('slot_id')
      .notNull()
      .references(() => slots.id, {
        onDelete: 'set null',
      }),
    bookingDate: text('booking_date').notNull(),
    startTime: text('start_time').notNull(),
    endTime: text('end_time').notNull(),
    status: text('status', { enum: ['confirmed', 'completed', 'cancelled'] })
      .notNull()
      .default('confirmed'),
    notes: text('notes'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('bookings_service_idx').on(columns.service),
    index('bookings_slot_idx').on(columns.slot),
    index('bookings_updated_at_idx').on(columns.updatedAt),
    index('bookings_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = sqliteTable(
  'payload_kv',
  {
    id: integer('id').primaryKey(),
    key: text('key').notNull(),
    data: text('data', { mode: 'json' }).notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    servicesID: integer('services_id'),
    slotsID: integer('slots_id'),
    bookingsID: integer('bookings_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_services_id_idx').on(columns.servicesID),
    index('payload_locked_documents_rels_slots_id_idx').on(columns.slotsID),
    index('payload_locked_documents_rels_bookings_id_idx').on(columns.bookingsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'payload_locked_documents_rels_services_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['slotsID']],
      foreignColumns: [slots.id],
      name: 'payload_locked_documents_rels_slots_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['bookingsID']],
      foreignColumns: [bookings.id],
      name: 'payload_locked_documents_rels_bookings_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const about_page_experience_highlights = sqliteTable(
  'about_page_experience_highlights',
  {
    _order: integer('_order').notNull(),
    _parentID: text('_parent_id').notNull(),
    id: text('id').primaryKey(),
    detail: text('detail').notNull(),
  },
  (columns) => [
    index('about_page_experience_highlights_order_idx').on(columns._order),
    index('about_page_experience_highlights_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page_experience.id],
      name: 'about_page_experience_highlights_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_experience = sqliteTable(
  'about_page_experience',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    organisation: text('organisation').notNull(),
    role: text('role').notNull(),
    location: text('location').notNull(),
    startDate: text('start_date').notNull(),
    endDate: text('end_date').notNull(),
    summary: text('summary').notNull(),
  },
  (columns) => [
    index('about_page_experience_order_idx').on(columns._order),
    index('about_page_experience_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_experience_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_specialties_areas = sqliteTable(
  'about_page_specialties_areas',
  {
    _order: integer('_order').notNull(),
    _parentID: text('_parent_id').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
  },
  (columns) => [
    index('about_page_specialties_areas_order_idx').on(columns._order),
    index('about_page_specialties_areas_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page_specialties.id],
      name: 'about_page_specialties_areas_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_specialties = sqliteTable(
  'about_page_specialties',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    title: text('title').notNull(),
    description: text('description').notNull(),
  },
  (columns) => [
    index('about_page_specialties_order_idx').on(columns._order),
    index('about_page_specialties_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_specialties_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_education = sqliteTable(
  'about_page_education',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    institution: text('institution').notNull(),
    degree: text('degree').notNull(),
    year: text('year').notNull(),
    result: text('result'),
  },
  (columns) => [
    index('about_page_education_order_idx').on(columns._order),
    index('about_page_education_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_education_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_certifications = sqliteTable(
  'about_page_certifications',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    title: text('title').notNull(),
    issuer: text('issuer'),
    year: text('year'),
  },
  (columns) => [
    index('about_page_certifications_order_idx').on(columns._order),
    index('about_page_certifications_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_certifications_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_languages = sqliteTable(
  'about_page_languages',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    proficiency: text('proficiency').notNull(),
  },
  (columns) => [
    index('about_page_languages_order_idx').on(columns._order),
    index('about_page_languages_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_languages_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page = sqliteTable(
  'about_page',
  {
    id: integer('id').primaryKey(),
    introduction_eyebrow: text('introduction_eyebrow').notNull(),
    introduction_name: text('introduction_name').notNull(),
    introduction_role: text('introduction_role').notNull(),
    introduction_location: text('introduction_location').notNull(),
    introduction_summary: text('introduction_summary').notNull(),
    introduction_philosophy: text('introduction_philosophy').notNull(),
    introduction_portrait: integer('introduction_portrait_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    contact_email: text('contact_email').notNull(),
    contact_phone: text('contact_phone').notNull(),
    contact_ctaLabel: text('contact_cta_label').notNull(),
    contact_ctaHeading: text('contact_cta_heading').notNull(),
    contact_ctaText: text('contact_cta_text').notNull(),
    updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('about_page_introduction_introduction_portrait_idx').on(columns.introduction_portrait),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_services = relations(services, ({ one }) => ({
  image: one(media, {
    fields: [services.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_slots = relations(slots, ({ one }) => ({
  service: one(services, {
    fields: [slots.service],
    references: [services.id],
    relationName: 'service',
  }),
}))
export const relations_bookings = relations(bookings, ({ one }) => ({
  service: one(services, {
    fields: [bookings.service],
    references: [services.id],
    relationName: 'service',
  }),
  slot: one(slots, {
    fields: [bookings.slot],
    references: [slots.id],
    relationName: 'slot',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: 'services',
    }),
    slotsID: one(slots, {
      fields: [payload_locked_documents_rels.slotsID],
      references: [slots.id],
      relationName: 'slots',
    }),
    bookingsID: one(bookings, {
      fields: [payload_locked_documents_rels.bookingsID],
      references: [bookings.id],
      relationName: 'bookings',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_about_page_experience_highlights = relations(
  about_page_experience_highlights,
  ({ one }) => ({
    _parentID: one(about_page_experience, {
      fields: [about_page_experience_highlights._parentID],
      references: [about_page_experience.id],
      relationName: 'highlights',
    }),
  }),
)
export const relations_about_page_experience = relations(
  about_page_experience,
  ({ one, many }) => ({
    _parentID: one(about_page, {
      fields: [about_page_experience._parentID],
      references: [about_page.id],
      relationName: 'experience',
    }),
    highlights: many(about_page_experience_highlights, {
      relationName: 'highlights',
    }),
  }),
)
export const relations_about_page_specialties_areas = relations(
  about_page_specialties_areas,
  ({ one }) => ({
    _parentID: one(about_page_specialties, {
      fields: [about_page_specialties_areas._parentID],
      references: [about_page_specialties.id],
      relationName: 'areas',
    }),
  }),
)
export const relations_about_page_specialties = relations(
  about_page_specialties,
  ({ one, many }) => ({
    _parentID: one(about_page, {
      fields: [about_page_specialties._parentID],
      references: [about_page.id],
      relationName: 'specialties',
    }),
    areas: many(about_page_specialties_areas, {
      relationName: 'areas',
    }),
  }),
)
export const relations_about_page_education = relations(about_page_education, ({ one }) => ({
  _parentID: one(about_page, {
    fields: [about_page_education._parentID],
    references: [about_page.id],
    relationName: 'education',
  }),
}))
export const relations_about_page_certifications = relations(
  about_page_certifications,
  ({ one }) => ({
    _parentID: one(about_page, {
      fields: [about_page_certifications._parentID],
      references: [about_page.id],
      relationName: 'certifications',
    }),
  }),
)
export const relations_about_page_languages = relations(about_page_languages, ({ one }) => ({
  _parentID: one(about_page, {
    fields: [about_page_languages._parentID],
    references: [about_page.id],
    relationName: 'languages',
  }),
}))
export const relations_about_page = relations(about_page, ({ one, many }) => ({
  introduction_portrait: one(media, {
    fields: [about_page.introduction_portrait],
    references: [media.id],
    relationName: 'introduction_portrait',
  }),
  experience: many(about_page_experience, {
    relationName: 'experience',
  }),
  specialties: many(about_page_specialties, {
    relationName: 'specialties',
  }),
  education: many(about_page_education, {
    relationName: 'education',
  }),
  certifications: many(about_page_certifications, {
    relationName: 'certifications',
  }),
  languages: many(about_page_languages, {
    relationName: 'languages',
  }),
}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  services: typeof services
  slots: typeof slots
  bookings: typeof bookings
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  about_page_experience_highlights: typeof about_page_experience_highlights
  about_page_experience: typeof about_page_experience
  about_page_specialties_areas: typeof about_page_specialties_areas
  about_page_specialties: typeof about_page_specialties
  about_page_education: typeof about_page_education
  about_page_certifications: typeof about_page_certifications
  about_page_languages: typeof about_page_languages
  about_page: typeof about_page
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_services: typeof relations_services
  relations_slots: typeof relations_slots
  relations_bookings: typeof relations_bookings
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_about_page_experience_highlights: typeof relations_about_page_experience_highlights
  relations_about_page_experience: typeof relations_about_page_experience
  relations_about_page_specialties_areas: typeof relations_about_page_specialties_areas
  relations_about_page_specialties: typeof relations_about_page_specialties
  relations_about_page_education: typeof relations_about_page_education
  relations_about_page_certifications: typeof relations_about_page_certifications
  relations_about_page_languages: typeof relations_about_page_languages
  relations_about_page: typeof relations_about_page
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
